version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.12.1
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  zmq_elasticsearch:
    build: .
    command: zmq_elasticsearch --socket-sub --connect-ip zmq_publisher --elastic-ip elasticsearch
    depends_on:
      - elasticsearch

  zmq_publisher:
    build: .
    environment:
      - BEARER_TOKEN
    ports:
      - "5556:5556"
    command: zmq_publisher --socket-pub --bind-ip 0.0.0.0
    depends_on:
      - zmq_elasticsearch

  kibana:
    image: kibana:7.12.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
